name:        rpgen
version:     v0.4.0
summary:     Generate a high entropy, memorable password.
description: Generate a high entropy, memorable password.
confinement: strict
base: core20
grade: stable

apps:
  rpgen:
    command: bin/rpgen
    plugs:
      - home

parts:
  rpgen:
    source: .
    plugin: npm
    npm-node-version: 14.3.0
