name:        rpgen
version:     v0.2.0
summary:     compile multiple scripts into a single cloud-init friendly script
description: compile multiple scripts into a single cloud-init friendly script
confinement: strict
base: core18
grade: stable

apps:
  rpgen:
    command: bin/rpgen

parts:
  rpgen:
    source: .
    plugin: nodejs
    nodejs-version: 14.3.0
    nodejs-package-manager: yarn
