name:        rpgen
version:     v0.3.0
summary:     Generate a high entropy, memorable password.
description: Generate a high entropy, memorable password.
confinement: strict
base: core18
grade: stable

apps:
  rpgen:
    command: bin/rpgen

parts:
  rpgen:
    source: .
    plugin: nodejs
    nodejs-version: 14.3.0
    nodejs-package-manager: yarn
