name:        rpgen
version:     v0.1.0
summary:     compile multiple scripts into a single cloud-init friendly script
description: compile multiple scripts into a single cloud-init friendly script

apps:
  rpgen:
    command: bin/rpgen

parts:
  rpgen:
    plugin: nodejs
    node-packages:
      - rgrannell1/rpgen
